// This configuration was generated by `exe/eslint_autogen`
// on 2026-03-11 22:31:10 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

import type {Linter} from "eslint";

const config: Linter.Config[] = [
  // Offense count: 2
  {
    files: [
      "app/javascript/channels/consumer.ts",
    ],
    rules: {
      "@stylistic/object-curly-spacing": "off",
    },
  },
  // Offense count: 2
  {
    files: [
      "app/javascript/channels/consumer.ts",
    ],
    rules: {
      "@stylistic/semi": "off",
    },
  },
  // Offense count: 5
  {
    files: [
      "spec/javascript/helpers/assert_spec.ts",
    ],
    rules: {
      "vitest/no-alias-methods": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/helpers/assert_spec.ts",
    ],
    rules: {
      "vitest/prefer-describe-function-title": "off",
    },
  },
  // Offense count: 47
  {
    files: [
      "app/javascript/controllers/hotkeys_controller.ts",
      "spec/javascript/application_spec.ts",
      "spec/javascript/channels/consumer_spec.ts",
      "spec/javascript/controllers/dialog_controller_spec.ts",
      "spec/javascript/controllers/hotkeys_controller_spec.ts",
      "spec/javascript/helpers/assert_spec.ts",
      "spec/javascript/setup.ts",
      "spec/javascript/support/stimulus.ts",
    ],
    rules: {
      "vitest/prefer-importing-vitest-globals": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/application_spec.ts",
    ],
    rules: {
      "vitest/prefer-strict-boolean-matchers": "off",
    },
  },
];

export default config;
