// This configuration was generated by `exe/eslint_autogen`
<<<<<<< HEAD
// on 2026-02-13 00:04:25 UTC.
=======
// on 2026-02-16 00:59:23 UTC.
>>>>>>> 1bbe39d (fix eslint_autogen script (#1341))
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

import type {Linter} from "eslint";

<<<<<<< HEAD
const eslintTodo: Linter.Config[] = [
  // Offense count: 2
  {
    files: [
      "app/javascript/channels/consumer.ts",
    ],
    rules: {
      "@stylistic/object-curly-spacing": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/application_spec.ts",
    ],
    rules: {
      "@stylistic/quotes": "off",
    },
  },
  // Offense count: 8
  {
    files: [
      "app/javascript/application.ts",
      "app/javascript/channels/consumer.ts",
    ],
    rules: {
      "@stylistic/semi": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/application_spec.ts",
    ],
    rules: {
      "vitest/prefer-to-be-truthy": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "app/javascript/application.ts",
    ],
    rules: {
      "vitest/require-hook": "off",
    },
  },
];

export default eslintTodo;
=======
const config: Linter.Config[] = [
];

export default config;
>>>>>>> 1bbe39d (fix eslint_autogen script (#1341))
