inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  EnabledByDefault: true
  Exclude: [node_modules/**/*, vendor/**/*, db/schema.rb]

################################################################################
#
# Rules that depart from rubocop defaults
#
################################################################################

# https://github.com/rubocop-hq/rubocop/issues/7841
Style/TrailingCommaInBlockArgs: { Enabled: false }
Layout/LineLength:
  Exclude:
    - 'config/**/*'
  AutoCorrect: true
Layout/TrailingEmptyLines: { Enabled: false }
Metrics/BlockLength:
  ExcludedMethods:
    - describe
  Exclude:
    - Guardfile
Rails/FilePath: { EnforcedStyle: slashes }
RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*.rb
RSpec/MessageExpectation: { EnforcedStyle: expect }
Style/CommentedKeyword: { Enabled: false }
Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - attr_accessor
    - attr_reader
    - attr_writer
    - belongs_to
    - cattr_accessor
    - context
    - default
    - delegate
    - describe
    - exec
    - exit
    - fit
    - gem
    - has_many
    - helper_method
    - include
    - it
    - layout
    - load
    - not_to
    - p
    - puts
    - rails_require
    - raise
    - require
    - require_relative
    - ruby
    - scope
    - source
    - store_accessor
    - to
    - validates
    - warn
  IgnoreMacros: false
  Exclude:
    - bin/**/*
    - 'config.ru'
    - 'config/boot.rb'
    - 'config/puma.rb'
    - 'config/routes.rb'
    - db/**/*.rb
    - Guardfile
    - Gemfile
Style/MixinUsage: { Exclude: ['bin/**/*'] }
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/StringLiteralsInInterpolation: { EnforcedStyle: double_quotes }
Style/SymbolArray: { EnforcedStyle: brackets }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: comma }
Style/WordArray: { EnforcedStyle: brackets }

################################################################################
#
# Rules we don't want to enable
#
################################################################################

Bundler/GemComment: { Enabled: false }
RSpec/AlignLeftLetBrace: { Enabled: false }
RSpec/AlignRightLetBrace: { Enabled: false }
Style/ConstantVisibility: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/DocumentationMethod: { Enabled: false }
Style/InlineComment: { Enabled: false }
Style/MissingElse: { Enabled: false }
Style/SafeNavigation: { Enabled: false }
Style/StringHashKeys: { Enabled: false }
